services:
  backend: 
    build:
      context: backend
      target: builder
    # flask requires SIGINT to stop gracefully
    # (default stop signal from Compose is SIGTERM)
    stop_signal: SIGINT
    ports:
      - '8000:8000'
    networks:
      - private
    volumes:
      - ./backend/:/app/
  frontend:
    build:
      context: frontend
      target: development
    ports:
      - '3000:5173'
    volumes:
      - ./frontend/src:/code/src
      - /code/node_modules
    networks:
      - private
    depends_on:
      - backend
networks:
  private:
